id: A655222BB
title: 'The Beautiful Rosary of Jewels: A Fulfilment Offering for Chimé Phakmé Nyingtik'
type: translation
pechas:
- IFE147807
- IA156E2BB
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:10:40.725285
  last_modified_at: 2023-01-04 12:10:40.725298
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IFE147807/1F14: 44ED
  IA156E2BB/C424: 44ED
